---
# tasks file for server
#

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - apache2
  - mysql-server
  - php-mysql
  - php
  - libapache2-mod-php
  - python3-mysqldb
